apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  name: kubeflow-pipelines-promise
spec:
  #To build workerClusterResources list run `go run ../../hack/worker-resource-builder/main.go -k8s-resources-directory ${PWD}/resources -promise ${PWD}/kubeflow-pipelines-promise-template.yaml > kubeflow-pipelines-promise.yaml`
  #workerClusterResources: 
  #  - kind: to be injected
  xaasRequestPipeline:
    - syntasso/kubeflow-pipelines-request-pipeline
  xaasCrd:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name:  kubeflow-pipelines.example.promise.syntasso.io
    spec:
      group: example.promise.syntasso.io
      scope: Namespaced
      names:
        plural: kubeflow-pipelines
        singular: kubeflow-pipelines
        kind: Kubeflow-pipelines
      versions:
        - name: v1
          schema:
            openAPIV3Schema:
              type: object
          served: true
          storage: true
