stateStores:
  - kind: GitStateStore
    name: default
    namespace: default
    secretRef:
      name: gitea-credentials
    path: "destinations"
    branch: main
    url: https://172.18.0.2:31333/gitea_admin/kratix

destinations:
  - name: worker-1
    namespace: default
    labels:
      environment: dev
    path: "dev"
    stateStoreRef:
      name: default
      kind: GitStateStore
