apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  name: knative-service
  namespace: default
spec:
  clusterSelector:
    environment: dev
  xaasCrd:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name:  knservices.example.promise.syntasso.io
    spec:
      group: example.promise.syntasso.io
      scope: Namespaced
      names:
        plural: knservices
        singular: knservice
        kind: knservice
      versions:
      - name: v1
        served: true
        storage: true
        schema:
          openAPIV3Schema:
            type: object
            properties:
              spec:
                type: object
                properties:
                  name: {type: string}
                  port:
                    type: number
                    default: 8080
                  image:
                    type: string
                  database:
                    type: object
                    properties:
                      host: { type: string }
                      user: { type: string }
                      secretKeyRef: { type: string }
                      name: { type: string }
  xaasRequestPipeline:
    - syntasso/kn-service-request-pipeline:v0.1.0
