---
apiVersion: example.promise.syntasso.io/v1
kind: knservice
metadata:
  name: app-request
  namespace: default
spec:
  name: todoapp
  image: syntasso/sample-todo-app
  port: 8080
  database:
    host: acid-tododb-postgresql.default.svc.cluster.local
    user: postgres
    secretKeyRef: postgres.acid-tododb-postgresql.credentials.postgresql.acid.zalan.do
    name: bestdb
