apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

# The wc-img-config config map drives the WC_IMG env var, which is used by the promise
# controller as the last container in the workflow Pipeline pod spec.
configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
- envs:
  - wc-img-config.properties
  name: wc-img-config

images:
- name: controller
  newName: syntasso/kratix-platform
  newTag: 02c0079e20f156dd618971e1695baac74bfa2726
