apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: appstack-example-app-app
  namespace: default
spec:
  paused: true # stop this killing my Docker account
  serviceAccountName: default-ns-sa
  fetch:
  - image:
      url: index.docker.io/syntasso/appstack-example-app
  template:
  - ytt:
      inline:
        paths:
          knative-serving.yml: |
            apiVersion: serving.knative.dev/v1
            kind: Service
            metadata:
              name: appstack-example-app
              namespace: default 
            spec:
              template:
                spec:
                  containers:
                  - image: index.docker.io/syntasso/appstack-example-app:latest
  deploy:
  - kapp: {}