version: 2.1

orbs:
  k8s: circleci/kubernetes@1.3.1
  golang: circleci/go@1.7.1

executors:
  machine-medium:
    machine: true
    working_directory: ~/repo
    resource_class: medium
  machine-large:
    machine: true
    working_directory: ~/repo
    resource_class: large

commands:
  install_software:
    steps:
      - k8s/install
      - golang/install:
          cache: true
          version: 1.17.13
      - run:
          name: Install Kind
          command: |
            if [ ! -f ~/bin/kind ]; then
              curl -L https://github.com/kubernetes-sigs/kind/releases/download/v0.14.0/kind-linux-amd64 -o ~/bin/kind
              chmod +x ~/bin/kind
            fi
      - checkout
      - run:
          name: Install Dependencies
          command: |
            go mod download

jobs:
  unit-tests:
    executor: machine-medium
    steps:
      - install_software
      - run:
          name: Run tests
          command: |
            make test
            make -C work-creator test

  int-tests:
    executor: machine-large
    steps:
      - install_software
      - run:
          name: Integration Tests
          command: |
            DOCKER_BUILDKIT=1 ACK_GINKGO_RC=true make --jobs=4 int-test

  e2e-demo-test:
    executor: machine-large
    steps:
      - install_software
      - run:
          name: Run quick-start script
          command: |
            make distribution
            DOCKER_BUILDKIT=1 make quick-start
      - run:
          name: Verify Jenkins
          command: |
            ./scripts/install-jenkins.sh

workflows:
  run-tests:
    jobs:
      - unit-tests
      - int-tests
      - e2e-demo-test
