version: 2.1

orbs:
  k8s: circleci/kubernetes@1.3.1
  golang: circleci/go@1.7.2

executors:
  machine-medium:
    machine: true
    working_directory: ~/repo
    resource_class: medium
  machine-large:
    machine: true
    working_directory: ~/repo
    resource_class: large

commands:
  docker_login:
    steps:
      - run:
          # https://circleci.com/docs/building-docker-images/#run-docker-commands-using-the-machine-executor
          name: Docker Auth
          command: |
            echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
  install_software:
    steps:
      - k8s/install
      - golang/install:
          cache: true
          version: 1.19.5
      - run:
          name: Install Kind
          command: |
            if [ ! -f ~/bin/kind ]; then
              curl -L https://github.com/kubernetes-sigs/kind/releases/download/v0.14.0/kind-linux-amd64 -o ~/bin/kind
              chmod +x ~/bin/kind
            fi
      - run:
          name: Install Helm
          command: |
            curl -L https://get.helm.sh/helm-v3.12.0-linux-amd64.tar.gz -o helm.tar.gz
            tar -xvf helm.tar.gz
            mv linux-amd64/helm ~/bin/helm
            chmod +x ~/bin/helm
      - run:
          name: Install yq
          command: |
            curl -L https://github.com/mikefarah/yq/releases/download/v4.34.1/yq_linux_amd64 -o yq
            mv yq ~/bin/yq
            chmod +x ~/bin/yq
      - run:
          name: Install Flux
          command: |
            curl -L https://github.com/fluxcd/flux2/releases/download/v0.41.2/flux_0.41.2_linux_amd64.tar.gz -o flux.tar.gz
            tar -xvf flux.tar.gz
            mv flux ~/bin/flux
            chmod +x ~/bin/flux
      - attach_workspace:
          at: .
      - run:
          name: Install Dependencies
          command: |
            go mod download
  setup_git:
    steps:
      - run:
          # see https://circleci.com/docs/github-integration#establish-the-authenticity-of-an-ssh-host
          name: setup git
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan github.com > ~/.ssh/known_hosts

            git config --global user.name "syntassodev"
            git config --global user.email "kratix@syntasso.io"

jobs:
  git-clone:
    executor: machine-medium
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .
  unit-tests:
    executor: machine-medium
    steps:
      - install_software
      - run:
          name: Run tests
          command: |
            make test
            make -C work-creator test

  system-tests:
    executor: machine-large
    steps:
      - install_software
      - run:
          name: System tests
          command: |
            DOCKER_BUILDKIT=1 ACK_GINKGO_RC=true make --jobs=4 system-test

  e2e-demo-test-helm-git:
    executor: machine-large
    steps:
      - install_software
      - run:
          name: Create clusters and helm install
          command: |
            make distribution
            export DOCKER_BUILDKIT=1

            # setup platform and install GitStateStore
            kind create cluster --image kindest/node:v1.24.0 --name platform --config hack/platform/kind-platform-config.yaml
            make build-and-load-kratix
            make build-and-load-worker-creator
            helm install kratix charts/kratix/ -f hack/platform/helm-values-gitea.yaml
            kubectl --context kind-platform apply --filename "hack/platform/gitea-install.yaml"
            kubectl --context kind-platform wait --for=condition=Ready --timeout=300s -n gitea pod -l app.kubernetes.io/instance=gitea

            # setup worker and register worker cluster
            kind create cluster --image kindest/node:v1.24.0 --name worker --config hack/worker/kind-worker-config.yaml
            helm install kratix-worker charts/kratix-worker/ -f hack/worker/helm-values-gitea.yaml
            kubectl --context kind-worker wait --for=condition=Ready --timeout=300s -n default kustomization kratix-workload-resources
      - run:
          name: Verify Jenkins
          command: |
            ./scripts/install-jenkins.sh

  e2e-demo-test-helm-bucket:
    executor: machine-large
    steps:
      - install_software
      - run:
          name: Create clusters and helm install
          command: |
            make distribution
            export DOCKER_BUILDKIT=1

            # setup platform and install BucketStateStore
            kind create cluster --image kindest/node:v1.24.0 --name platform --config hack/platform/kind-platform-config.yaml
            make build-and-load-kratix
            make build-and-load-worker-creator
            helm install kratix charts/kratix/ -f hack/platform/helm-values-minio.yaml
            kubectl --context kind-platform apply --filename "hack/platform/minio-install.yaml"
            kubectl --context kind-platform wait --for=condition=Ready --timeout=300s -n kratix-platform-system pod -l run=minio

            # setup worker and register worker cluster
            kind create cluster --image kindest/node:v1.24.0 --name worker --config hack/worker/kind-worker-config.yaml
            helm install kratix-worker charts/kratix-worker/ -f hack/worker/helm-values-minio.yaml
            kubectl --context kind-platform apply --filename config/samples/platform_v1alpha1_worker_cluster.yaml
            kubectl --context kind-worker wait --for=condition=Ready --timeout=300s -n kratix-worker-config kustomization kratix-workload-resources
      - run:
          name: Verify Jenkins
          command: |
            ./scripts/install-jenkins.sh

  git-merge:
    executor: machine-large
    steps:
      - install_software
      - setup_git
      - run:
          name: Merge dev to main
          command: |
            ./scripts/merge-dev.sh
      - persist_to_workspace:
          root: .
          paths:
            - .

  generate-demo-image-list:
    executor: machine-large
    steps:
      - attach_workspace:
          at: .
      - install_software
      - run:
          name: Generate demo image list
          command: |
            cd ./demo/
            ./scripts/generate-demo-image-list.sh
      - persist_to_workspace:
          root: .
          paths:
            - .

  build-and-push-images:
    executor: machine-large
    parameters:
      image:
        type: string
    steps:
      - attach_workspace:
          at: .
      - docker_login
      - run:
          name: Build and push sample images
          command: |
            ./scripts/build-images << parameters.image >>

  git-push:
    executor: machine-large
    steps:
      - attach_workspace:
          at: .
      - add_ssh_keys:
          # Add github deploy key
          # https://circleci.com/docs/github-integration#create-a-github-deploy-key
          fingerprints:
            - "5e:1e:ea:52:8b:1b:ad:a2:66:1a:40:98:a3:f5:96:f5"
      - setup_git
      - run:
          name: Push main
          command: |
            git add -f config/
            git add -f demo/demo-image-list
            git add -f distribution/kratix.yaml
            git add -f distribution/single-cluster/
            git add -f charts/kratix/crds/platform_kratix_io_crds.yaml
            git add -f charts/kratix/templates/distribution.yaml
            git commit --amend --no-edit
            git push origin main

workflows:
  run-tests:
    jobs:
      - git-clone
      - unit-tests:
          requires: [git-clone]
      - system-tests:
          requires: [git-clone]
      - e2e-demo-test-helm-bucket:
          requires: [git-clone]
      - e2e-demo-test-helm-git:
          requires: [git-clone]
      - git-merge:
          requires:
            - unit-tests
            - system-tests
            - e2e-demo-test-helm-git
            - e2e-demo-test-helm-bucket
          filters:
            branches:
              only: dev
      - build-and-push-images:
          requires: [git-merge]
          matrix:
            parameters:
              image: [kratix, work-creator, samples]
      - git-push:
          requires:
            - build-and-push-images
