apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: TBDNAME
  namespace: TBDNAMESPACE
spec:
  ingress:
    kourier:
      enabled: true
  config:
    domain:
      "local.gd": ""
    network:
      ingress-class: "kourier.ingress.networking.knative.dev"
