# permissions for end users to view bucketstatestores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bucketstatestore-viewer-role
rules:
- apiGroups:
  - platform.kratix.io
  resources:
  - bucketstatestores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - platform.kratix.io
  resources:
  - bucketstatestores/status
  verbs:
  - get
