# permissions for end users to edit bucketstatestores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bucketstatestore-editor-role
rules:
- apiGroups:
  - platform.kratix.io
  resources:
  - bucketstatestores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.kratix.io
  resources:
  - bucketstatestores/status
  verbs:
  - get
