# permissions for end users to view gitstatestores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitstatestore-viewer-role
rules:
- apiGroups:
  - platform.kratix.io
  resources:
  - gitstatestores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - platform.kratix.io
  resources:
  - gitstatestores/status
  verbs:
  - get
