# permissions for end users to edit promises.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: promise-editor-role
rules:
- apiGroups:
  - platform.kratix.io
  resources:
  - promises
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.kratix.io
  resources:
  - promises/status
  verbs:
  - get
