# permissions for end users to view promises.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: promise-viewer-role
rules:
- apiGroups:
  - platform.synpl.syntasso.io
  resources:
  - promises
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - platform.synpl.syntasso.io
  resources:
  - promises/status
  verbs:
  - get
