# permissions for end users to edit statestores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: statestore-editor-role
rules:
- apiGroups:
  - platform.kratix.io
  resources:
  - statestores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.kratix.io
  resources:
  - statestores/status
  verbs:
  - get
