# permissions for end users to view workplacements.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workplacement-viewer-role
rules:
- apiGroups:
  - platform.kratix.io
  resources:
  - workplacements
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - platform.kratix.io
  resources:
  - workplacements/status
  verbs:
  - get
