# permissions for end users to edit workplacements.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workplacement-editor-role
rules:
- apiGroups:
  - platform.kratix.io
  resources:
  - workplacements
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.kratix.io
  resources:
  - workplacements/status
  verbs:
  - get
