# permissions for end users to edit works.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: work-editor-role
rules:
- apiGroups:
  - platform.synpl.syntasso.io
  resources:
  - works
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.synpl.syntasso.io
  resources:
  - works/status
  verbs:
  - get
