# Default values for kratix-worker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

flux:
  # install flux, set to false if using a prexisting flux installation
  install: true

config:
  path: "" # Path in StateStore. See https://kratix.io/docs/main/reference/clusters/intro
  namespace: "" # Namespace to create config
  secretRef:
    name: "" # Name of secret
    #   # Optional values; if ommited assumes secret already exists
    #   values:
    #   for GitStateStore:
    #     username: "" # Base64 encoded
    #     password: "" # Base64 encoded
    #   for BucketStateStore:
    #     accessKeyID: "" # Base64 encoded
    #     secretAccessKey: "" # Base64 encoded
  git: {}
    # Example
    # url: "https://github.com/syntasso/kratix-repo"
    # branch: "main"
  # If using a BucketStateStore
  bucket: {}
    # Example
    # insecure: false
    # endpoint: "s3.amazonaws.com"
    # bucket: "my-org-kratix-platform"


