---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: NAME-knative-jenkins-deployer
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: NAME-knative-jenkins-deployer-rolebinding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: NAME-knative-jenkins-deployer-role
subjects:
  - kind: ServiceAccount
    name: NAME-knative-jenkins-deployer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: NAME-knative-jenkins-deployer-role
  namespace: default
rules:
  - apiGroups:
      - serving.knative.dev
    resources:
      - services
    verbs:
      - "*"
