apiVersion: platform.kratix.syntasso.io/v1alpha1
kind: Promise
metadata:
  name: promise-sample
spec:
  crd:
    apiVersion: something
    kind: Redis
    metadata:
      name: redis.pennys-platform.acme.io
    spec:
      group: pennys-platform.acme.io
      names:
        kind: Redis
        listKind: RedisList
        plural: Redii
        singular: Redis
      scope: Namespaced