apiVersion: platform.kratix.io/v1alpha1
kind: PromiseRelease
metadata:
  labels:
    app.kubernetes.io/name: promiserelease
    app.kubernetes.io/instance: promiserelease-sample
    app.kubernetes.io/part-of: kratix
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kratix
  name: promiserelease-sample
spec:
  # TODO(user): Add fields here
