apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  creationTimestamp: null
  name: spicy-dev-environment-promise
  namespace: default
spec:
  xaasCrd:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: spicydevenvironments.example.promise.syntasso.io
    spec:
      group: example.promise.syntasso.io
      names:
        kind: spicydevenvironment
        plural: spicydevenvironments
        singular: spicydevenvironment
      scope: Namespaced
      versions:
      - name: v1
        schema:
          openAPIV3Schema:
            properties:
              spec:
                properties:
                  gcpSecretName:
                    type: string
                  gcpServiceAccount:
                    type: string
                  gcpProject:
                    type: string
                  minioEndpoint:
                    type: string
                type: object
            type: object     
        served: true
        storage: true
  xaasRequestPipeline:
  - syntasso/spicy-dev-environment-request-pipeline