apiVersion: kpack.io/v1alpha1
kind: Image
metadata:
  name: <tbr-applicationName>
  namespace: default
spec:
  tag: <tbr-appImageTag>
  serviceAccount: <tbr-applicationName>-service-account
  builder:
    name: <tbr-applicationName>-builder
    kind: Builder
  source:
    git:
      url: <tbr-gitRepo>
      revision: main
