apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  name: ha-postgres-promise
  namespace: default
spec:
  #To build wrokerResources list run `worker-resource-builder -k8s-resources-directory ${PWD}/resources -promise ${PWD}/postgres-promise-template.yaml > postgres-promise.yaml`
  #workerClusterResources: 
  #  - kind: to be injected
  xaasRequestPipeline:
    - syntasso/postgres-request-pipeline
  xaasCrd:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
     name:  postgreses.example.promise.syntasso.io
    spec:
     group: example.promise.syntasso.io
     scope: Namespaced
     names:
       plural: postgreses
       singular: postgres 
       kind: postgres
     versions:
       - name: v1
         served: true
         storage: true
         schema:
           openAPIV3Schema:
             type: object
             properties:
               spec:
                 type: object
                 properties:
                   preparedDatabases:
                     additionalProperties:
                       properties:
                         defaultUsers:
                           type: boolean
                         extensions:
                           additionalProperties:
                             type: string
                           type: object
                         schemas:
                           additionalProperties:
                             properties:
                               defaultRoles:
                                 type: boolean
                               defaultUsers:
                                 type: boolean
                             type: object
                           type: object
                       type: object
                     type: object
                  