---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: Bucket 
metadata:
  name: CLUSTER_NAME-workload-crds 
  namespace: flux-system
spec:
  interval: 10s
  provider: generic
  bucketName: CLUSTER_NAME-kratix-crds
  endpoint: ENDPOINT
  insecure: true
  secretRef:
    name: minio-credentials
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: Bucket 
metadata:
  name: CLUSTER_NAME-workload-resources 
  namespace: flux-system
spec:
  interval: 10s
  provider: generic
  bucketName: CLUSTER_NAME-kratix-resources
  endpoint: ENDPOINT
  insecure: true
  secretRef:
    name: minio-credentials
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: flux-system
type: Opaque
data:
  accesskey: bWluaW9hZG1pbg==
  secretkey: bWluaW9hZG1pbg== 
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: CLUSTER_NAME-workload-resources 
  namespace: flux-system 
spec:
  interval: 5s
  prune: true
  dependsOn: 
    - name: CLUSTER_NAME-workload-crds
  sourceRef:
    kind: Bucket 
    name: CLUSTER_NAME-workload-resources 
  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: CLUSTER_NAME-workload-crds 
  namespace: flux-system 
spec:
  interval: 5s
  prune: true
  sourceRef:
    kind: Bucket 
    name: CLUSTER_NAME-workload-crds 
  validation: client  