on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: trigger-run-ci
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
          CCI_TARGET_SLUG: ${{ secrets.CCI_TARGET_SLUG }}
          GHA_META: ${{ github.event.release.tag_name }}
        run: |
          curl -H "Circle-Token: ${CCI_TOKEN}" \
            -H 'content-type: application/json' \
            -d '{"parameters":{"Trigger_Actor":"syntassodev","Trigger_Action":"trigger-run-ci","Trigger_Event":"release","Trigger_Meta":"'${GHA_META}'"}}' \
            https://circleci.com/api/v2/project/${CCI_TARGET_SLUG}/pipeline
